### ISSUE TITLE
User Profile: Main Task

### ISSUE THREAD

**Issue by xanderbakx** [Do-Jest-While-True/cooked#19]
Subtasks:
- [x] User Profile Screen #20 
- [x] User API Routes #21
- [x] Auth API Routes #24
