### ISSUE TITLE
Login/Signup: Main Task

### ISSUE THREAD

**Issue by xanderbakx** [Do-Jest-While-True/cooked#22]
Subtasks:

- [x] Login/Signup Screen #25
- [ ] OAuth/Passport Console Setup #26
- [ ] OAuth/Passport server code #27
- [x] Login&Logout/Signup POST routes #28
