### ISSUE TITLE
Subtask of #74 Comments: Link Comments to Posts

### ISSUE THREAD

**Issue by bryanryu1** [Do-Jest-While-True/cooked#75]
Link up the comment vertical slice to posts

- [ ] add button/input form for comments into single post view
- [ ] display comment count on list view
- [ ] comment should display username of the user who commented
